version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: app-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: post_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
